using Core2D.Serializer.Xaml;
using Portable.Xaml.Markup;

[assembly: XmlnsDefinition(XamlConstants.BaseNamespace, "Core2D", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.BaseNamespace, "Core2D.Attributes", AssemblyName = "Core2D")]

[assembly: XmlnsDefinition(XamlConstants.ModelNamespace, "Core2D", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ModelNamespace, "Core2D.Containers", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ModelNamespace, "Core2D.Data", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ModelNamespace, "Core2D.Renderer", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ModelNamespace, "Core2D.Renderer.Presenters", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ModelNamespace, "Core2D.History", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ModelNamespace, "Core2D.Interfaces", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ModelNamespace, "Core2D.Path", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ModelNamespace, "Core2D.Shapes", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ModelNamespace, "Core2D.Style", AssemblyName = "Core2D")]

[assembly: XmlnsDefinition(XamlConstants.ViewModelsNamespace, "Core2D.Containers", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ViewModelsNamespace, "Core2D.Data", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ViewModelsNamespace, "Core2D.Renderer", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ViewModelsNamespace, "Core2D.Shapes", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ViewModelsNamespace, "Core2D.Shapes.Path", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ViewModelsNamespace, "Core2D.Shapes.Path.Segments", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.ViewModelsNamespace, "Core2D.Style", AssemblyName = "Core2D")]

[assembly: XmlnsDefinition(XamlConstants.EditorNamespace, "Core2D.Editor", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.EditorNamespace, "Core2D.Editor.Bounds", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.EditorNamespace, "Core2D.Editor.Bounds.Shapes", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.EditorNamespace, "Core2D.Editor.Designer", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.EditorNamespace, "Core2D.Editor.Factories", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.EditorNamespace, "Core2D.Editor.Input", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.EditorNamespace, "Core2D.Editor.Recent", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.EditorNamespace, "Core2D.Editor.Tools", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.EditorNamespace, "Core2D.Editor.Tools.Path.Settings", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.EditorNamespace, "Core2D.Editor.Tools.Path.Shapes", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.EditorNamespace, "Core2D.Editor.Tools.Selection", AssemblyName = "Core2D")]
[assembly: XmlnsDefinition(XamlConstants.EditorNamespace, "Core2D.Editor.Tools.Settings", AssemblyName = "Core2D")]

[assembly: XmlnsDefinition(XamlConstants.SpatialNamespace, "Spatial", AssemblyName = "Math.Spatial")]
[assembly: XmlnsDefinition(XamlConstants.SpatialNamespace, "Spatial.Arc", AssemblyName = "Math.Spatial")]
[assembly: XmlnsDefinition(XamlConstants.SpatialNamespace, "Spatial.ConvexHull", AssemblyName = "Math.Spatial")]
[assembly: XmlnsDefinition(XamlConstants.SpatialNamespace, "Spatial.DouglasPeucker", AssemblyName = "Math.Spatial")]
[assembly: XmlnsDefinition(XamlConstants.SpatialNamespace, "Spatial.Sat", AssemblyName = "Math.Spatial")]

[assembly: XmlnsDefinition(XamlConstants.DockNamespace, "Dock.Model", AssemblyName = "Dock.Model")]

[assembly: XmlnsPrefix(XamlConstants.ModelNamespace, "b")]
[assembly: XmlnsPrefix(XamlConstants.ModelNamespace, "m")]
[assembly: XmlnsPrefix(XamlConstants.ModelNamespace, "vm")]
[assembly: XmlnsPrefix(XamlConstants.EditorNamespace, "e")]
[assembly: XmlnsPrefix(XamlConstants.SpatialNamespace, "s")]
[assembly: XmlnsPrefix(XamlConstants.DockNamespace, "c")]
