//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2d.UI.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test2d.UI.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string ContainerBackground {
            get {
                return ResourceManager.GetString("ContainerBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ContainerHeight {
            get {
                return ResourceManager.GetString("ContainerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ContainerName {
            get {
                return ResourceManager.GetString("ContainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string ContainerProperties {
            get {
                return ResourceManager.GetString("ContainerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string ContainerTemplate {
            get {
                return ResourceManager.GetString("ContainerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ContainerWidth {
            get {
                return ResourceManager.GetString("ContainerWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Data.
        /// </summary>
        public static string MenuData {
            get {
                return ResourceManager.GetString("MenuData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export....
        /// </summary>
        public static string MenuDataExport {
            get {
                return ResourceManager.GetString("MenuDataExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import....
        /// </summary>
        public static string MenuDataImport {
            get {
                return ResourceManager.GetString("MenuDataImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cl_ear All.
        /// </summary>
        public static string MenuEditClearAll {
            get {
                return ResourceManager.GetString("MenuEditClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string MenuEditCopy {
            get {
                return ResourceManager.GetString("MenuEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy As _Metafile.
        /// </summary>
        public static string MenuEditCopyAsEmf {
            get {
                return ResourceManager.GetString("MenuEditCopyAsEmf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        public static string MenuEditCut {
            get {
                return ResourceManager.GetString("MenuEditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string MenuEditDelete {
            get {
                return ResourceManager.GetString("MenuEditDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De_select All.
        /// </summary>
        public static string MenuEditDeselectAll {
            get {
                return ResourceManager.GetString("MenuEditDeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Group.
        /// </summary>
        public static string MenuEditGroup {
            get {
                return ResourceManager.GetString("MenuEditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Order.
        /// </summary>
        public static string MenuEditOrder {
            get {
                return ResourceManager.GetString("MenuEditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring Fo_rward.
        /// </summary>
        public static string MenuEditOrderBringForward {
            get {
                return ResourceManager.GetString("MenuEditOrderBringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to _Front.
        /// </summary>
        public static string MenuEditOrderBringToFront {
            get {
                return ResourceManager.GetString("MenuEditOrderBringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Ba_ckward.
        /// </summary>
        public static string MenuEditOrderSendBackward {
            get {
                return ResourceManager.GetString("MenuEditOrderSendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to _Back.
        /// </summary>
        public static string MenuEditOrderSendToBack {
            get {
                return ResourceManager.GetString("MenuEditOrderSendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string MenuEditPaste {
            get {
                return ResourceManager.GetString("MenuEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string MenuEditRedo {
            get {
                return ResourceManager.GetString("MenuEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _All.
        /// </summary>
        public static string MenuEditSelectAll {
            get {
                return ResourceManager.GetString("MenuEditSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string MenuEditUndo {
            get {
                return ResourceManager.GetString("MenuEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_ngroup.
        /// </summary>
        public static string MenuEditUngroup {
            get {
                return ResourceManager.GetString("MenuEditUngroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string MenuFileClose {
            get {
                return ResourceManager.GetString("MenuFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export....
        /// </summary>
        public static string MenuFileExport {
            get {
                return ResourceManager.GetString("MenuFileExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Group....
        /// </summary>
        public static string MenuFileExportGroup {
            get {
                return ResourceManager.GetString("MenuFileExportGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gro_up Libraries....
        /// </summary>
        public static string MenuFileExportGroupLibraries {
            get {
                return ResourceManager.GetString("MenuFileExportGroupLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr_oup Library....
        /// </summary>
        public static string MenuFileExportGroupLibrary {
            get {
                return ResourceManager.GetString("MenuFileExportGroupLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G_roups....
        /// </summary>
        public static string MenuFileExportGroups {
            get {
                return ResourceManager.GetString("MenuFileExportGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Style....
        /// </summary>
        public static string MenuFileExportStyle {
            get {
                return ResourceManager.GetString("MenuFileExportStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sty_le Libraries....
        /// </summary>
        public static string MenuFileExportStyleLibraries {
            get {
                return ResourceManager.GetString("MenuFileExportStyleLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St_yle Library....
        /// </summary>
        public static string MenuFileExportStyleLibrary {
            get {
                return ResourceManager.GetString("MenuFileExportStyleLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_tyles....
        /// </summary>
        public static string MenuFileExportStyles {
            get {
                return ResourceManager.GetString("MenuFileExportStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Template....
        /// </summary>
        public static string MenuFileExportTemplate {
            get {
                return ResourceManager.GetString("MenuFileExportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_emplates....
        /// </summary>
        public static string MenuFileExportTemplates {
            get {
                return ResourceManager.GetString("MenuFileExportTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Group....
        /// </summary>
        public static string MenuFileImportGroup {
            get {
                return ResourceManager.GetString("MenuFileImportGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gro_up Libraries....
        /// </summary>
        public static string MenuFileImportGroupLibraries {
            get {
                return ResourceManager.GetString("MenuFileImportGroupLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr_oup Library....
        /// </summary>
        public static string MenuFileImportGroupLibrary {
            get {
                return ResourceManager.GetString("MenuFileImportGroupLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G_roups....
        /// </summary>
        public static string MenuFileImportGroups {
            get {
                return ResourceManager.GetString("MenuFileImportGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Style....
        /// </summary>
        public static string MenuFileImportStyle {
            get {
                return ResourceManager.GetString("MenuFileImportStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sty_le Libraries....
        /// </summary>
        public static string MenuFileImportStyleLibraries {
            get {
                return ResourceManager.GetString("MenuFileImportStyleLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St_yle Library....
        /// </summary>
        public static string MenuFileImportStyleLibrary {
            get {
                return ResourceManager.GetString("MenuFileImportStyleLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_tyles....
        /// </summary>
        public static string MenuFileImportStyles {
            get {
                return ResourceManager.GetString("MenuFileImportStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Template....
        /// </summary>
        public static string MenuFileImportTemplate {
            get {
                return ResourceManager.GetString("MenuFileImportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_emplates....
        /// </summary>
        public static string MenuFileImportTemplates {
            get {
                return ResourceManager.GetString("MenuFileImportTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string MenuFileNew {
            get {
                return ResourceManager.GetString("MenuFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recent.
        /// </summary>
        public static string MenuFileRecent {
            get {
                return ResourceManager.GetString("MenuFileRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MenuFileSave {
            get {
                return ResourceManager.GetString("MenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string MenuFileSaveAs {
            get {
                return ResourceManager.GetString("MenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expor_t.
        /// </summary>
        public static string MenuFileSubMenuExport {
            get {
                return ResourceManager.GetString("MenuFileSubMenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_mport.
        /// </summary>
        public static string MenuFileSubMenuImport {
            get {
                return ResourceManager.GetString("MenuFileSubMenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default is Close_d.
        /// </summary>
        public static string MenuOptionsDefaultIsClosed {
            get {
                return ResourceManager.GetString("MenuOptionsDefaultIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default is _Filled.
        /// </summary>
        public static string MenuOptionsDefaultIsFilled {
            get {
                return ResourceManager.GetString("MenuOptionsDefaultIsFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default is Smooth _Join.
        /// </summary>
        public static string MenuOptionsDefaultIsSmoothJoin {
            get {
                return ResourceManager.GetString("MenuOptionsDefaultIsSmoothJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default is Stro_ked.
        /// </summary>
        public static string MenuOptionsDefaultIsStroked {
            get {
                return ResourceManager.GetString("MenuOptionsDefaultIsStroked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to _Grid.
        /// </summary>
        public static string MenuOptionsSnapToGrid {
            get {
                return ResourceManager.GetString("MenuOptionsSnapToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try To _Connect.
        /// </summary>
        public static string MenuOptionsTryToConnect {
            get {
                return ResourceManager.GetString("MenuOptionsTryToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path T_ool.
        /// </summary>
        public static string MenuPathTool {
            get {
                return ResourceManager.GetString("MenuPathTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Arc.
        /// </summary>
        public static string MenuPathToolArc {
            get {
                return ResourceManager.GetString("MenuPathToolArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Bezier.
        /// </summary>
        public static string MenuPathToolBezier {
            get {
                return ResourceManager.GetString("MenuPathToolBezier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Line.
        /// </summary>
        public static string MenuPathToolLine {
            get {
                return ResourceManager.GetString("MenuPathToolLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Move.
        /// </summary>
        public static string MenuPathToolMove {
            get {
                return ResourceManager.GetString("MenuPathToolMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _QBezier.
        /// </summary>
        public static string MenuPathToolQBezier {
            get {
                return ResourceManager.GetString("MenuPathToolQBezier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te_mplate.
        /// </summary>
        public static string MenuTemplate {
            get {
                return ResourceManager.GetString("MenuTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tool.
        /// </summary>
        public static string MenuTool {
            get {
                return ResourceManager.GetString("MenuTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Arc.
        /// </summary>
        public static string MenuToolArc {
            get {
                return ResourceManager.GetString("MenuToolArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Bezier.
        /// </summary>
        public static string MenuToolBezier {
            get {
                return ResourceManager.GetString("MenuToolBezier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ellipse.
        /// </summary>
        public static string MenuToolEllipse {
            get {
                return ResourceManager.GetString("MenuToolEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Image.
        /// </summary>
        public static string MenuToolImage {
            get {
                return ResourceManager.GetString("MenuToolImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Line.
        /// </summary>
        public static string MenuToolLine {
            get {
                return ResourceManager.GetString("MenuToolLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _None.
        /// </summary>
        public static string MenuToolNone {
            get {
                return ResourceManager.GetString("MenuToolNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pat_h.
        /// </summary>
        public static string MenuToolPath {
            get {
                return ResourceManager.GetString("MenuToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Point.
        /// </summary>
        public static string MenuToolPoint {
            get {
                return ResourceManager.GetString("MenuToolPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _QBezier.
        /// </summary>
        public static string MenuToolQBezier {
            get {
                return ResourceManager.GetString("MenuToolQBezier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Rectangle.
        /// </summary>
        public static string MenuToolRectangle {
            get {
                return ResourceManager.GetString("MenuToolRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Selection.
        /// </summary>
        public static string MenuToolSelection {
            get {
                return ResourceManager.GetString("MenuToolSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Text.
        /// </summary>
        public static string MenuToolText {
            get {
                return ResourceManager.GetString("MenuToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co_ntainer.
        /// </summary>
        public static string MenuViewContainerWindow {
            get {
                return ResourceManager.GetString("MenuViewContainerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Databases.
        /// </summary>
        public static string MenuViewDatabasesWindow {
            get {
                return ResourceManager.GetString("MenuViewDatabasesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data_base Window.
        /// </summary>
        public static string MenuViewDatabaseWindow {
            get {
                return ResourceManager.GetString("MenuViewDatabaseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data W_indow.
        /// </summary>
        public static string MenuViewDataWindow {
            get {
                return ResourceManager.GetString("MenuViewDataWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc_ument Window.
        /// </summary>
        public static string MenuViewDocumentWindow {
            get {
                return ResourceManager.GetString("MenuViewDocumentWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Groups.
        /// </summary>
        public static string MenuViewGroupsWindow {
            get {
                return ResourceManager.GetString("MenuViewGroupsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Layers.
        /// </summary>
        public static string MenuViewLayersWindow {
            get {
                return ResourceManager.GetString("MenuViewLayersWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string MenuViewOptionsWindow {
            get {
                return ResourceManager.GetString("MenuViewOptionsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project E_xplorer.
        /// </summary>
        public static string MenuViewProjectWindow {
            get {
                return ResourceManager.GetString("MenuViewProjectWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prop_erties Window.
        /// </summary>
        public static string MenuViewPropertiesWindow {
            get {
                return ResourceManager.GetString("MenuViewPropertiesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sh_apes.
        /// </summary>
        public static string MenuViewShapesWindow {
            get {
                return ResourceManager.GetString("MenuViewShapesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State _Window.
        /// </summary>
        public static string MenuViewStateWindow {
            get {
                return ResourceManager.GetString("MenuViewStateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Styles.
        /// </summary>
        public static string MenuViewStylesWindow {
            get {
                return ResourceManager.GetString("MenuViewStylesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St_yle Window.
        /// </summary>
        public static string MenuViewStyleWindow {
            get {
                return ResourceManager.GetString("MenuViewStyleWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Templates.
        /// </summary>
        public static string MenuViewTemplatesWindow {
            get {
                return ResourceManager.GetString("MenuViewTemplatesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te_mplate Window.
        /// </summary>
        public static string MenuViewTemplateWindow {
            get {
                return ResourceManager.GetString("MenuViewTemplateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zoom.
        /// </summary>
        public static string MenuViewZoom {
            get {
                return ResourceManager.GetString("MenuViewZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable _Autofit.
        /// </summary>
        public static string MenuViewZoomAutofit {
            get {
                return ResourceManager.GetString("MenuViewZoomAutofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to _Extent.
        /// </summary>
        public static string MenuViewZoomExtent {
            get {
                return ResourceManager.GetString("MenuViewZoomExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset Zoom.
        /// </summary>
        public static string MenuViewZoomReset {
            get {
                return ResourceManager.GetString("MenuViewZoomReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        public static string MenuWindow {
            get {
                return ResourceManager.GetString("MenuWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load Layout....
        /// </summary>
        public static string MenuWindowLoadLayout {
            get {
                return ResourceManager.GetString("MenuWindowLoadLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset Layout.
        /// </summary>
        public static string MenuWindowResetLayout {
            get {
                return ResourceManager.GetString("MenuWindowResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save Layout....
        /// </summary>
        public static string MenuWindowSaveLayout {
            get {
                return ResourceManager.GetString("MenuWindowSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FillRule.
        /// </summary>
        public static string OptionsDefaultFillRule {
            get {
                return ResourceManager.GetString("OptionsDefaultFillRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsClosed.
        /// </summary>
        public static string OptionsDefaultIsClosed {
            get {
                return ResourceManager.GetString("OptionsDefaultIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsFilled.
        /// </summary>
        public static string OptionsDefaultIsFilled {
            get {
                return ResourceManager.GetString("OptionsDefaultIsFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSmoothJoin.
        /// </summary>
        public static string OptionsDefaultIsSmoothJoin {
            get {
                return ResourceManager.GetString("OptionsDefaultIsSmoothJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsStroked.
        /// </summary>
        public static string OptionsDefaultIsStroked {
            get {
                return ResourceManager.GetString("OptionsDefaultIsStroked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string OptionsHeaderAdvanced {
            get {
                return ResourceManager.GetString("OptionsHeaderAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        public static string OptionsHeaderDefaults {
            get {
                return ResourceManager.GetString("OptionsHeaderDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string OptionsHeaderGeneral {
            get {
                return ResourceManager.GetString("OptionsHeaderGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelperStyle.
        /// </summary>
        public static string OptionsHelperStyle {
            get {
                return ResourceManager.GetString("OptionsHelperStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HitTreshold.
        /// </summary>
        public static string OptionsHitTreshold {
            get {
                return ResourceManager.GetString("OptionsHitTreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveMode.
        /// </summary>
        public static string OptionsMoveMode {
            get {
                return ResourceManager.GetString("OptionsMoveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PointShape.
        /// </summary>
        public static string OptionsPointShape {
            get {
                return ResourceManager.GetString("OptionsPointShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PointStyle.
        /// </summary>
        public static string OptionsPointStyle {
            get {
                return ResourceManager.GetString("OptionsPointStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectionStyle.
        /// </summary>
        public static string OptionsSelectionStyle {
            get {
                return ResourceManager.GetString("OptionsSelectionStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SnapToGrid.
        /// </summary>
        public static string OptionsSnapToGrid {
            get {
                return ResourceManager.GetString("OptionsSnapToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SnapX.
        /// </summary>
        public static string OptionsSnapX {
            get {
                return ResourceManager.GetString("OptionsSnapX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SnapY.
        /// </summary>
        public static string OptionsSnapY {
            get {
                return ResourceManager.GetString("OptionsSnapY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TryToConnect.
        /// </summary>
        public static string OptionsTryToConnect {
            get {
                return ResourceManager.GetString("OptionsTryToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ProjectOptions {
            get {
                return ResourceManager.GetString("ProjectOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containers.
        /// </summary>
        public static string StatusContainers {
            get {
                return ResourceManager.GetString("StatusContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string StatusDocuments {
            get {
                return ResourceManager.GetString("StatusDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string StatusLayers {
            get {
                return ResourceManager.GetString("StatusLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string StatusNoContainers {
            get {
                return ResourceManager.GetString("StatusNoContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string StatusNoDocuments {
            get {
                return ResourceManager.GetString("StatusNoDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string StatusNoLayers {
            get {
                return ResourceManager.GetString("StatusNoLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string StatusNoSelected {
            get {
                return ResourceManager.GetString("StatusNoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string StatusNoShapes {
            get {
                return ResourceManager.GetString("StatusNoShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofit.
        /// </summary>
        public static string StatusOptionsAutofit {
            get {
                return ResourceManager.GetString("StatusOptionsAutofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string StatusOptionsClosed {
            get {
                return ResourceManager.GetString("StatusOptionsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string StatusOptionsConnect {
            get {
                return ResourceManager.GetString("StatusOptionsConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled.
        /// </summary>
        public static string StatusOptionsFilled {
            get {
                return ResourceManager.GetString("StatusOptionsFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmoothJoin.
        /// </summary>
        public static string StatusOptionsSmoothJoin {
            get {
                return ResourceManager.GetString("StatusOptionsSmoothJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap.
        /// </summary>
        public static string StatusOptionsSnap {
            get {
                return ResourceManager.GetString("StatusOptionsSnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroked.
        /// </summary>
        public static string StatusOptionsStroked {
            get {
                return ResourceManager.GetString("StatusOptionsStroked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc.
        /// </summary>
        public static string StatusPathToolArc {
            get {
                return ResourceManager.GetString("StatusPathToolArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezier.
        /// </summary>
        public static string StatusPathToolBezier {
            get {
                return ResourceManager.GetString("StatusPathToolBezier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string StatusPathToolLine {
            get {
                return ResourceManager.GetString("StatusPathToolLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string StatusPathToolMove {
            get {
                return ResourceManager.GetString("StatusPathToolMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QBezier.
        /// </summary>
        public static string StatusPathToolQBezier {
            get {
                return ResourceManager.GetString("StatusPathToolQBezier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string StatusSelected {
            get {
                return ResourceManager.GetString("StatusSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: 1.
        /// </summary>
        public static string StatusSelectedOne {
            get {
                return ResourceManager.GetString("StatusSelectedOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        public static string StatusShapes {
            get {
                return ResourceManager.GetString("StatusShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc.
        /// </summary>
        public static string StatusToolArc {
            get {
                return ResourceManager.GetString("StatusToolArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezier.
        /// </summary>
        public static string StatusToolBezier {
            get {
                return ResourceManager.GetString("StatusToolBezier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        public static string StatusToolEllipse {
            get {
                return ResourceManager.GetString("StatusToolEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string StatusToolImage {
            get {
                return ResourceManager.GetString("StatusToolImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string StatusToolLine {
            get {
                return ResourceManager.GetString("StatusToolLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string StatusToolNone {
            get {
                return ResourceManager.GetString("StatusToolNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string StatusToolPath {
            get {
                return ResourceManager.GetString("StatusToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string StatusToolPoint {
            get {
                return ResourceManager.GetString("StatusToolPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QBezier.
        /// </summary>
        public static string StatusToolQBezier {
            get {
                return ResourceManager.GetString("StatusToolQBezier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string StatusToolRectangle {
            get {
                return ResourceManager.GetString("StatusToolRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string StatusToolSelection {
            get {
                return ResourceManager.GetString("StatusToolSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string StatusToolText {
            get {
                return ResourceManager.GetString("StatusToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string WindowTitleContainer {
            get {
                return ResourceManager.GetString("WindowTitleContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string WindowTitleData {
            get {
                return ResourceManager.GetString("WindowTitleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string WindowTitleDatabase {
            get {
                return ResourceManager.GetString("WindowTitleDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        public static string WindowTitleDatabases {
            get {
                return ResourceManager.GetString("WindowTitleDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string WindowTitleDocument {
            get {
                return ResourceManager.GetString("WindowTitleDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string WindowTitleGroups {
            get {
                return ResourceManager.GetString("WindowTitleGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string WindowTitleLayers {
            get {
                return ResourceManager.GetString("WindowTitleLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string WindowTitleOptions {
            get {
                return ResourceManager.GetString("WindowTitleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string WindowTitleProject {
            get {
                return ResourceManager.GetString("WindowTitleProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string WindowTitleProperties {
            get {
                return ResourceManager.GetString("WindowTitleProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        public static string WindowTitleShapes {
            get {
                return ResourceManager.GetString("WindowTitleShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string WindowTitleState {
            get {
                return ResourceManager.GetString("WindowTitleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string WindowTitleStyle {
            get {
                return ResourceManager.GetString("WindowTitleStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string WindowTitleStyles {
            get {
                return ResourceManager.GetString("WindowTitleStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string WindowTitleTemplate {
            get {
                return ResourceManager.GetString("WindowTitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string WindowTitleTemplates {
            get {
                return ResourceManager.GetString("WindowTitleTemplates", resourceCulture);
            }
        }
    }
}
